# There is no automatic conversion between int and float
KBT = 0.00411
conMaxIte = 1000
conResTol = 0.00001
conSolverChoice = 0
dt = 0.00001
monolayer = false
particleBufferAABB = 0.5
particleFixed = false
rngSeed = 1234
simBoxHigh = [30.0, 30.0, 30.0]
simBoxLow = [0.0, 0.0, 0.0]
simBoxPBC = [true, true, false]
timeSnap = 0.001
timeTotal = 0.1
viscosity = 0.01
