# There is no automatic conversion between int and float
KBT = 0.00411
conMaxIte = 1000
conResTol = 0.00001
conSolverChoice = 0
monolayer = false
particleBufferAABB = 0.5
particleFixed = false
resume = true
rngSeed = 1234
simBoxHigh = [30.0, 30.0, 30.0]
simBoxLow = [0.0, 0.0, 0.0]
simBoxPBC = [true, true, false]
timeSnap = 0.001
timeTotal = 0.02
timedt = 0.0001
viscosity = 0.01
